### ISSUE TITLE
为什么会出现loss降不下去的情况

### ISSUE THREAD

**Issue by SunEternal** [zhengyanzhao1997/NLP-model#4]
哪怕是一个batch的样本差别很大，也应该有一些作用吧

**Comment by zhengyanzhao1997** [comment]
请说明是哪个项目，是否有对数据和代码进行改动哈

**Comment by SunEternal** [comment]
SimCSE的无监督训练，在自己的数据集上，主要是借鉴了对比学习的损失函数，但是似乎并没有起到作用。

**Comment by zhengyanzhao1997** [comment]
1. 是否保证了在一个batch中每一个样本都有对应的唯一正样本
2. 相似度矩阵和标签矩阵是否构建对应

**Comment by SunEternal** [comment]
是的，一个batch中构造的方式是[01，23，45……]，01，23这些位置都是一样的样本

**Comment by zhengyanzhao1997** [comment]
可以抽一个batch的原始文本数据看看吗

**Comment by SunEternal** [comment]
sorry，我想我知道我哪里出错了，构造的过程是没问题的，但是shuffle的时候把它的顺序打乱了，我需要重新预处理一下数据，谢谢您啦
